apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        env: prod
    spec:
      containers:
        - name: nginx
          image: mirror.gcr.io/library/nginx:1.27.0
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
